### ISSUE TITLE
validation mistaken integer field with datetime

### ISSUE THREAD

**Issue by om4csaba** [zapier/zapier-platform#212]
### Bug Description

Upon `zapier validate` I receive a warning:
```
│ Category    │ Warnings                                                           │
│ Method      │ triggers.subscriptionHook                                          │
│ Description │ field "version" is not a valid ISO-8601 date (D023)                │
│ Link        │ https://platform.zapier.com/docs/integration-checks-reference#D023 |
```
But that field is an integer:

```json
{
    "key": "version",
    "helpText": "Version of WooCommerce which last updated the order.",
    "type": "integer"
}
```
### Reproduction Steps

Perhaps the "updated" word in the description confuses the validator (contains the string `date`).

### Version Info

- Version info: zapier-platform-cli/9.4.0 darwin-x64 node-v10.20.1
- Operating System: macOS 10.15.4
- App id: 67372

**Comment by xavdid** [comment]
You can safely ignore that warning, it looks like there's a bug on our end somewhere. Are you looking at the `v2.0.3` code that's pushed, or do you have local changes?

**Comment by zapzap** [comment]
This issue has been copied into our private issue tracker  (as [PDE-1508](https://zapierorg.atlassian.net/browse/PDE-1508)). Thanks for the report! We'll update this as we learn more.

**Comment by om4csaba** [comment]
@xavdid Thanks for the reply!

This warning appears for us for a while. No local changes need to reproduce.  Yes, I know I can ignore the warnings. But it is a false positive warning, that why I reported it.

**Comment by eliangcs** [comment]
Sorry for the late reply!

This check is designed to be aggressive so we don't miss any mistakes. The way it is implemented is we pass the value to a datetime parser. If it doesn't error, we say the value looks like a datetime and it should follow the ISO format.

You have this value in your sample:

```
{
  "version": "2.6.0"
}
```

"2.6.0" is interpreted to 2000-02-06 by the datetime parser without an error and it doesn't follow the ISO format. That's why you saw the false positive warning.

If you really don't like the warning, you can make it go away by replacing `2.6.0` with `2.0.0`, because `2.0.0` doesn't look like a datetime given how we implement the check.

Closing without a fix.
