### ISSUE TITLE
Dynamically created line items not handled correctly

### ISSUE THREAD

**Issue by NormanStevens** [zapier/zapier-platform#236]
### Bug Description

You can dynamically create input fields in an action. This can include line items fields, i.e. a field which and array of child fields in an array under the key "children".

When the action is performed the values in bundle.inputData do not include the line items array

For a set of line items defined in the inputFields array we get the following in bundle.inputData.

```js
    {
        line_items: [
            {
                id: 1
                name: "first item",
            }
            ...
        ],
        id: "1,2,3",
        name: "first item,second item,third item",
    }

```

But for a set of line items created by using a function in the inputFields you only get
```js
    {
        id: "1,2,3",
        name: "first item,second item,third item",
    }
```

### Reproduction Steps

1. Add a set of line items dynamically

```js
    inputFields: [
    {
        key: 'document_header_id',
        label: 'Order Id',
        helpText: 'Id of the order to which these line items belong',
        required: true,
        type: 'integer',
    },
    getInputFields,
    ];

    function getInputFields (z, bundle) {
    ...
    return { key: 'line_Items' : children: line_item_fields };
    }
```

### Version Info

- Version info: zapier-platform-cli/10.0.0 darwin-x64 node-v10.20.1
- Operating System: macOS Catalina 10.5.5
- App id: 29251

---
_DB: edited for syntax_

**Comment by eliangcs** [comment]
For developers who are running into this and whose integration was converted from Web Builder, this is caused by the `loadCustomFieldsEarly` property, which is a boolean designed to retain the legacy Web Builder behavior so the integration doesn't break when we upgrade it to the new platform (i.e. the visual builder and the CLI). If you want to switch to the new behavior in the CLI, find the `loadCustomFieldsEarly` property and set it to true.

**Comment by xitonix** [comment]
Hi guys. Any updates on this issue?
