### ISSUE TITLE
making multipart/form-data requests

### ISSUE THREAD

**Issue by codekirei** [zapier/zapier-platform#26]
It would be nice to have either a section in the docs or a dedicated example app that shows how to make a multipart/form-data request from a CLI app.

There are a lot of NPM modules out there that help with this &mdash; it might be interesting to experiment with some of those (i.e. https://www.npmjs.com/package/form-data).

**Comment by vasanthv** [comment]
Any updates on this? If it's already available, can someone point me to the right direction.

**Comment by vasanthv** [comment]
Found it myself. https://github.com/zapier/zapier-platform-example-app-files/blob/master/creates/uploadFile.js

**Comment by xavdid** [comment]
oh awesome! Glad that's there.

**Comment by robertoibarra** [comment]
I was posting a file from my connector to a PHP script but it turned out that there is some issue in PHP that when you post multipart/form-data using 'Transfer-Encoding: chunked' PHP just doesn't populate neither the $_POST nor $_FILES variables so you get nothing, except a 200 OK returned. However, everything works if you use the "Content-Length" header alternative which FormData (the form-data NPM package) uses in its formData.submit method. You can post the FormData object with other modules like z.request but they don't use the Content-Length header, careful. 

I based my connector code on https://github.com/zapier/zapier-platform/blob/master/example-apps/files/creates/uploadFile_v10.js and instead of using a [z.request](https://github.com/zapier/zapier-platform/blob/876b4d30f1a59779f3cc774074275a2c609a0963/example-apps/files/creates/uploadFile_v10.js#L22) to post the form I used the following code from https://stackoverflow.com/a/64885619

So it was something like:
`
async function makeRequest(formData, options) {
...
}
const perform = async (z, bundle) => {
const form = new FormData();
form.append('myfile', stream, { filename: bundle.inputData.filename });

const options = {...};
const res = await makeRequest(form, options);
return z.JSON.parse(res);
};
`
