### ISSUE TITLE
performSubscribe zap id

### ISSUE THREAD

**Issue by coonmoo** [zapier/zapier-platform#276]
It seems  bundle.meta.zap.id has been removed from the documentation.
Is there any way to get the Zap ID when subscribe is called?

We'd like to be able to have the user being redirect to edit the Zap on zapier.com by adding a link from our dashboard webhook subscriptions overview.

**Comment by xavdid** [comment]
Looks like that section was removed from the docs in error - `bundle.meta.zap.id` is still present in subscribe and unsubscribe bundles. I'll re-add it.

**Comment by coonmoo** [comment]
@xavdid is there another way to get the Zap id?

**Comment by xavdid** [comment]
There's not - we're doing some architectural changes in the backend and as a result, will be moving away from Zap IDs being a thing. So, best not to rely on it.

**Comment by jgoclawski** [comment]
@xavdid What is the recommended approach to listing Zaps connected with the app if `zap.id` gets deleted one day?

Our app has a dashboard that can list all registered Zapier hooks. We thought it would enhance user experience a lot, if we could provide a link to edit each zap in Zapier. Something like a list of Zaps connected and a link to Zapier next to them.
We planned to use `bundle.meta.zap.id` and `bundle.meta.zap.link`. It works at the moment, but then I found this issue and it made me worry.

**Comment by xavdid** [comment]
@jgoclawski great question! that's a use case for our [Partner API](https://platform.zapier.com/partner_api/introduction), which will provide a live list of zaps. That'll be more reliable than generating and storing a list of your own based on runtime bundles.

**Comment by rymndhng** [comment]
@xavdid We have a similar issue here, and we are also using the Partner API. We need a reference to the zap.id so that we can render our webhook information beside the response from the partner API. 

Now we're seeing the value of `bundle.meta.zap.id: "subscription:<some-id>"`. Is there an API available to resolve the subscription id to a zap id from the partner API?

**Comment by xavdid** [comment]
> Is there an API available to resolve the subscription id to a zap id from the partner API? - @rymndhng 

There isn't - subscriptions are no longer a 1:1 with zaps (that is, 2+ zaps can share a subscription), so as a result you can't map back to a zap based on a hook body. 

Could you explain a little more about your use case here? We can't change the `bundle.meta.zap.id` format, but we might be able to arrive at a different solution!

**Comment by om4csaba** [comment]
Hi @xavdid 

We also used the `bundle.meta.zap.id` to map the Zap from WooCommerce. 
Here is an example:

![task-list](https://user-images.githubusercontent.com/45931795/129124150-c3c4cc10-cdec-49cd-8381-018c783f1c05.png)

**Comment by ikbelkirasan** [comment]
@xavdid How can we make 2+ zaps share a subscription?

**Comment by xavdid** [comment]
@ikbelkirasan That's an internal mechanism, developers don't have direct control over it. From the outside, the zap runtime keeps working like it always has (minus this notable change in the `bundle.meta.zap.id`)

**Comment by rymndhng** [comment]
You are correct, that the Zapier integration continues to send zaps correctly. The part that's broken is how the change has broken our UI for configuring & viewing zapier integrations.

We have a workflow that showcases Zap Templates embedded in Unbounce. This allows customers to select **one or more** zap templates and set it up per Landing Page. We previously used the `bundle.meta.zap.id` property to associate Integrations in our product (Unbounce) with Zapier Partner API. See the example on this page: https://platform.zapier.com/partner_api/examples, this is our application.

Our application makes API requests to `api.zapier.com/v1/zaps` to fetch the zaps, however we cannot merge the response with our Integrations in the UI, because `id` values do not line up. It creates a poor user experience on our end.

See this example, we have no way of correlating our integrations with Zaps because the `id` no longer matches.

This is what our UI used to look like with working zap ids:

![Screen Shot 2021-08-17 at 5 26 43 PM](https://user-images.githubusercontent.com/1694040/129817591-7e1142fd-7c65-410c-9bc1-dfe6ab161baf.png)

This is what it looks like now, notice that we have "Zap Information Unavailable" because we can't correlate our Integrations with Zaps.

![Screen Shot 2021-08-17 at 5 23 31 PM](https://user-images.githubusercontent.com/1694040/129817403-d6f11529-240a-4194-bfd4-e46921f80c9d.png)

---

If there's some API that can do either of these things, we can restore our application functionality:
1. Provide an API to resolve subscription_id `->` zap_id`.
2.Enrich the `v1/zaps` API response to include a list of subscription_ids.

**Comment by xavdid** [comment]
Thanks for that context @rymndhng. I may be misunderstanding, but do you need data from `bundle.zap` here? Seems like you could use rely on the partner API's `/zaps` endpoint exclusively.

**Comment by rymndhng** [comment]
The `/zaps` endpoint satisfies _most_ of our feature set, however we need the `bundle.zap.id` to build a UI to correlate errors/retry of webhooks to zapier.

**Comment by stevefisherdev** [comment]
Hey! Following up here for Ray.

Our customers can add multiple Zaps to their pages. When a visitor submits a form on our customer's page, we send the lead to _all_ of the Zaps. 

Here's the steps that are causing our problem:

1. On subscribe, we store the `zap.id` and the `targetUrl`
2. If a webhook delivery fails (like timeout/unavailable), we create an error for that `zap.id` with the `lead_id`
3. When our customer views their integrations page, we retrieve the list of Zaps from the Partner API
4. We display the list of Zaps on the page
5. We use(d) the `zap.id` to find which Zap in the Partner API response caused the error(s)
6. We allow the user to re-submit the error'ed lead if they choose

With this new API change, it is impossible to associate the Partner API Zaps to the information we store during subscription. We don't get the correct `zap.id` anymore, and we also don't get a `targetUrl` for the Zap. As an example, a user could have 5 Zaps configured, and not know which Zap the lead would be re-submitted to.

Some solutions that come to mind would be:

1. Include the _set_ of subscription IDs for each Zap in the Partner API
2. Add a separate API to map a subscription ID to a Zap ID

**Comment by bcooksey** [comment]
Hey folks, thanks for giving us feedback and examples of how you are using `zap.id` and `targetUrl` in your products. Those are interesting use cases.

For the time being, the change of `zap.id` to the subscription id is not a change we can reverse. It's part of a larger technical overhaul we are doing and we have to keep the system this way. I'm sorry for any work that entails on your all's sides to update UIs to work with the more limited data.

Distilling the feedback down, what it sounds like would solve each use case is if the `/zaps` endpoint in the Partner API also included the `targetUrl`. That would enable you to link up Zaps to failed hook delivery. I've passed that request along to the team that maintains the Partner API so they know about the interest. To set expectations, I don't think this is going to be high enough priority for them tackle soon (I'm think a couple quarters at least). We've got other exciting things in the works that we want to deliver for our shared customers.

Appreciate the feedback and the thoughts.
