### ISSUE TITLE
Confused at bundle object

### ISSUE THREAD

**Issue by YSMScn** [zapier/zapier-platform#312]
I am confused at bundle object after reading thought document. Now I know that bundle object contains auth data that will pass to my app by zapier.  My question is, how can i set this bundle object to let zapier knows those auth data. like auth.email or domain url.
Thanks, I know this question is quite stupid

**Comment by xavdid** [comment]
Not a dumb question at all! 

You define authentication for your app, which in turn defines a number of fields (such as password, api key, etc) ([docs](https://github.com/zapier/zapier-platform/blob/master/packages/cli/README.md#authentication)).

https://github.com/zapier/zapier-platform/blob/b9719de6f900196c18fe60f865e4cc312993e90d/example-apps/custom-auth/authentication.js#L50 

When executing a trigger, you can safely assume that all the auth fields have been filled out. Whatever fields are in `authentication.fields` will be in `bundle.authData` under their `key`. So that API Key example above will be available at  `bundle.authData.apiKey`. 

Does that make sense?
