### ISSUE TITLE
How to include event name in performSubscribe hook

### ISSUE THREAD

**Issue by opsb** [zapier/zapier-platform#41]
My understanding is that when a subscription is created via rest hooks it should include a name for the particular event that the user is interested in e.g. `user_registered`. The server is then able to trigger rest hooks at the appropriate times. I haven't been able to find any documentation for the performSubscribe hook showing how to include this event name, is it available on the bundle somehow?

**Comment by xavdid** [comment]
Hey there!

You can include arbitrary data in the subscription hook. There's an example here: https://github.com/zapier/zapier-platform/blob/e8d4fc588bdb2a15059a151057b607a8057b0a06/example-apps/rest-hooks/triggers/recipe.js#L6-L9

You can add any data you would find helpful on your end.

**Comment by opsb** [comment]
I have to confess I'm a little confused, I was under the impression that when a subscription was added it was for a particular trigger (at least that's how the UX seems when creating a Zap). If the server that the Zap subscribes to doesn't know which trigger the subscription is for, how does it know when to fire?

**Comment by xavdid** [comment]
> when a subscription was added it was for a particular trigger

Correct. Even more specifically, it's for an instance of a trigger. I could have two "New Contact" zaps that would each get a (presumably identical) payload when a new contact is created. 

The reason subscriptions are so open-ended is to make them compatible with a wide range of server setups. Imagine these two scenarios:

1. Your server has a hook endpoint for each resource type (`/hooks/contacts`, `/hooks/emails`, etc). When a hook zap turns on, it makes an authenticated request to the appropriate endpoint (the "New Contact" and "New Email" triggers know where they should report). On your server, you know that there's a new subscription for contacts, it belongs to user `1234` (because the request is authenticated), and that new contacts for that users account should be sent to the provided url.
2. Your server has a single endpoint for all hooks (`/hooks`). When a zap turns on, the `performSubscribe` method needs to make a request that includes the string `contact` or `email`. The result is the same though - the server gets a new subscription for user `1234` concerning new `contacts` and a url to which those payloads should go.

In either case, when a new contact is created on your end, you look up whom it belongs to (user `1234`), find all active hooks (there could be 0+), and iterate through them, sending a POST request with info about the new contact to each.

Does that clear it up a little bit?

**Comment by opsb** [comment]
@xavdid that clears things up nicely, many thanks!

**Comment by opsb** [comment]
@xavdid your comments make a lot of sense when using the zapnito UI platform, each trigger has configuration for it's own urls for subscribe/unsubscribe/perform. With the CLI things aren't so clear though. Instead of each trigger have it's own configuration for the urls, you have a single performSubscribe/performUnsubscribe for all triggers. If these callbacks don't receive the trigger name then I'm not sure how I can subscribe to that particular trigger's resthook on the server.

**Comment by opsb** [comment]
To be a little more concrete, I was expecting to be able to do something like this
```
const subscribe = (z, bundle) => {
  const options = {
    url: "https://server.com/rest-hooks/${bundle.triggerName}",
    method: "POST"
  };

  // make the request and parse the response - this does not include any error handling.
  return z.request(options).then(response => z.JSON.parse(response.content));
};
```

**Comment by opsb** [comment]
nvm, found https://github.com/zapier/zapier-platform-example-app-rest-hooks/blob/master/triggers/recipe.js#L1-L22 which shows that the subscribe/unsubscribe callbacks are in fact on the trigger not the index.
