### ISSUE TITLE
How to retrieve element of http response headers from response of a Token Exchange Request?

### ISSUE THREAD

**Issue by anupa1234** [zapier/zapier-platform#549]
### Current Behavior
I am using Session auth to integrate zapier with our app.
Our app response cookie as a http response header in a token exchange request. I would like to use cookie in sub sequent request. I tried to fetch it with z.console.log(response.headers['set-cookie']); but it always shows un-defined. 
![3](https://user-images.githubusercontent.com/30339993/170518162-448ff124-70fe-49e2-ad56-d7b5940d584c.png)

![2](https://user-images.githubusercontent.com/30339993/170516605-b00c18eb-0362-40b1-b82f-4c8d79ac13b7.png)

### Desired Behavior
z.console.log(response.headers['set-cookie']); should return cookie that got from response.

**Comment by eliangcs** [comment]
Sorry for the late reply!

Does your app server redirect the request? If so, `set-cookie` isn't there because you're probably getting it from the redirected response. To stop `z.request` from redirecting, set `follow` to false:

```
const options = {
  url: '...',
  follow: false,
};
return z.request(options).then((response) => {
  const results = response.data;
  z.console.log(response.headers['set-cookie']);
  return results;
});
```

I'm closing this, but feel free to reopen if ☝️ doesn't fix it for you. Thanks!
