### ISSUE TITLE
prebuilt templates are not responsive

### ISSUE THREAD

**Issue by anmol1905** [zapier/zapier-platform#563]
### Bug Description

When opening zapier's website on phone, most of the pages are responsive for mobile. But when I click on any recommended zap then the website shrinks to the top left corner

### Reproduction Steps

1. login with your account
2. scroll down to see recommended zaps
3. click on try it. that's it the screen will be unresponsive
![image](https://user-images.githubusercontent.com/77231592/182846730-c0f079ac-ddc4-4f98-98f1-67e5c576a7c4.png)

**Comment by kreddlear** [comment]
Hi there @anmol1905 , this repo is dedicated to the Zapier Integration Platform, rather than the general Zapier product, and therefore isn't checked regularly for bug reports about the general Zapier product. If you're still running into this issue, please reach out to our Support team at this link: https://zapier.com/app/get-help so that they can take a look and help you out.
