### ISSUE TITLE
Error: "https://zapier.com/api/platform/cli/check" returned "400" saying "App must validate against schema before running app checks"

### ISSUE THREAD

**Issue by lpellegr** [zapier/zapier-platform#597]
I am updating a Zapier CLI app. While running `zapier build`, I get the following error:

> ✔ Copying project to temp directory 
> ✔ Installing project dependencies 
> ✔ Applying entry point file 
> ✔ Building app definition.json 
> ✖ Validating project style › Error: "https://zapier.com/api/platform/cli/check" returned "400" saying "App must validate against schema before running app checks"

Note that `npm run build` passes with no problems.

Here is my _.zapierapprc_ content:

> { "id": 3375, "key": "App1570" }

Using `zapier build --debug` or `zapier validate --debug` gives no more information.

I have no idea how to fix this. Any help?

Note that I already tried removing _node_modules/_, _package-lock.json_, and running again `npm install`. Always has the same error.

Here are the versions used:

```
$ zapier -v
* CLI version: 12.2.0
* Node.js version: v19.1.0
* OS info: linux-x64
* `zapier-platform-core` dependency: 12.2.0
```

**Comment by rnegron** [comment]
Hello @lpellegr! Thanks for including all that debug info! The exception `App must validate against schema before running app checks` means that the specific CLI integration version is not passing our remote JSON Schema validation. What is the result of running `zapier validate` on your end? The output there should help pinpoint where the problem is.

As for `npm run build` working, that would depend on what you have defined as the custom `build` script in your CLI integration's `package.json` file. It may or may not be calling `zapier build`, which would be worth double checking.

If it helps, you can also optionally skip validation during the build step with the `--skip-validation` flag: `zapier build --skip-validation`. The `--skip-validation` flag is also available in the `zapier push`, although I would recommended not skipping validation when pushing unless necessary.

**Comment by whutomo** [comment]
Hi @rnegron . I am actually facing the same issue when running `zapier validate`. I am expecting that I would be able to see what the issue is if the schema validation throws any errors. But all I am getting is exactly the same as the title of the issue above. 

I tried running `zapier validate --debug` but it does not give me any meaningful clues as to what is the root of the issue.
Here's the error that I am getting with the `--debug` flag passed in 

```
Running integration checks
  zapier:validate Error: "https://zapier.com/api/platform/cli/check" returned "400" saying "App must validate against schema before running app checks"
  zapier:validate     at /Users/harryutomo/.nvm/versions/node/v16.15.1/lib/node_modules/zapier-platform-cli/src/utils/api.js:137:17
  zapier:validate     at processTicksAndRejections (node:internal/process/task_queues:96:5)
  zapier:validate     at async ValidateCommand.perform (/Users/harryutomo/.nvm/versions/node/v16.15.1/lib/node_modules/zapier-platform-cli/src/oclif/commands/validate.js:57:21)
  zapier:validate     at async Promise.all (index 1)
  zapier:validate     at async ValidateCommand._run (/Users/harryutomo/.nvm/versions/node/v16.15.1/lib/node_modules/zapier-platform-cli/node_modules/@oclif/command/lib/command.js:43:20)
  zapier:validate     at async Config.runCommand (/Users/harryutomo/.nvm/versions/node/v16.15.1/lib/node_modules/zapier-platform-cli/node_modules/@oclif/config/lib/config.js:173:24)
  zapier:validate     at async Main.run (/Users/harryutomo/.nvm/versions/node/v16.15.1/lib/node_modules/zapier-platform-cli/node_modules/@oclif/command/lib/main.js:28:9)
  zapier:validate     at async Main._run (/Users/harryutomo/.nvm/versions/node/v16.15.1/lib/node_modules/zapier-platform-cli/node_modules/@oclif/command/lib/command.js:43:20) +1s
 ›   Error: "https://zapier.com/api/platform/cli/check" returned "400" saying "App must validate against schema before running app checks"
```

here is the version that I used 
```
* CLI version: 13.0.0
* Node.js version: v16.15.1
* OS info: darwin-arm64
* `zapier-platform-core` dependency: 12.2.0
```

**Comment by Kay-pet** [comment]
I am getting the same response on `zapier validate --debug` unable to pinpoint the validation error. I am hoping someone follows up on this considering it was not solved

**Comment by wolfGecko** [comment]
I had the same error. In my case it was a typo in my `outputFields.js`, specifically an extra `,` at the end of the line from a find/replace. Not a generic solution by any means, but probably worth checking for similar for whoever sees this next.

**Comment by ikegentz** [comment]
> I had the same error. In my case it was a typo in my `outputFields.js`, specifically an extra `,` at the end of the line from a find/replace. Not a generic solution by any means, but probably worth checking for similar for whoever sees this next.

Wow had the EXACT same thing - thank you!

Regarding the original issue itself, `zapier validate` isn't very useful if it itself can't detect the invalid state. Error message is not helpful and should be updated

**Comment by hopzebordah** [comment]
For anyone who got here because they were stuck with the `Error: "https://zapier.com/api/platform/cli/check" returned "400" saying "App must validate against schema before running app checks"` message and were getting an unhelpful message when running with the `--debug` flag: the debug output prints the JSON-ified structure of your project which is then sent to Zapier's validation endpoint, which is what's returning the 400. If you prettify that JSON representation of your project, you might be able to get a clue as to what the issue is - in my case, one of my `beforeRequest` functions was named incorrectly. It was showing in the JSON as `undefined` which is what clued me into what was causing the validation error
