### ISSUE TITLE
Integration vs app?

### ISSUE THREAD

**Issue by bradleyayers** [zapier/zapier-platform#75]
In the web UI, it looks like apps have been renamed to integrations—is that correct? If so, it seems like zapier-platform has not been updated with this new name, which is causing me some confusion.

**Comment by eliangcs** [comment]
You're right. "App" mentioned in this repo should be "integration" most of the time. Sorry for the confusion. We probably won't change it for now because it's going to be a big effort and a breaking change. But we certainly should make it more clear in our docs. Will close this once we have the doc.

**Comment by bradleyayers** [comment]
Understandable :) My wish would be for it to be updated everywhere, but the old `apps` command kept for backwards compatibility (in addition to a new `integrations` command). Regardless, thanks for the clarification.
